databases:
  - name: flashcardsdb   
    plan: free
    databaseName: flashcards
    user: flashcards

services:
  - type: web
    plan: free
    name: flashcards 
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn flashcards.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL 
        fromDatabase:
          name: flashcardsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: "flashcards.settings.production"
      - key: DJANGO_ENV
        value: "production"
 