# Generated by Django 4.2.16 on 2024-11-22 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deckshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deckshare',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='deckshare',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='deckshare',
            name='shared_with',
        ),
        migrations.AlterUniqueTogether(
            name='userdeck',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userdeck',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='userdeck',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcards'},
        ),
        migrations.AlterModelOptions(
            name='usercardprogress',
            options={'ordering': ['next_review_date']},
        ),
        migrations.RenameField(
            model_name='usercardprogress',
            old_name='last_review_result',
            new_name='card_due_for_review',
        ),
        migrations.RenameField(
            model_name='usercardprogress',
            old_name='round_completed',
            new_name='card_mastered',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_study_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_cards_studied',
        ),
        migrations.AddField(
            model_name='card',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Image file for the card', upload_to='card_images/'),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='anishinaabemowin',
            field=models.CharField(help_text='The Anishinaabemowin word or phrase', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio file for the card', upload_to='card_audio/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_in_deck', to='cards.deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='english',
            field=models.CharField(help_text='The English translation', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='example_sentence',
            field=models.TextField(blank=True, help_text='Example sentence using the Anishinaabemowin word'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pronunciation',
            field=models.CharField(blank=True, help_text='Pronunciation of the Anishinaabemowin word', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='subject',
            field=models.CharField(blank=True, help_text='The category or subject area of the card', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usercardprogress',
            unique_together={('user', 'card')},
        ),
        migrations.AddIndex(
            model_name='usercardprogress',
            index=models.Index(fields=['user', 'next_review_date'], name='cards_userc_user_id_f6f4db_idx'),
        ),
        migrations.AddIndex(
            model_name='usercardprogress',
            index=models.Index(fields=['user', 'box_level'], name='cards_userc_user_id_72c33c_idx'),
        ),
        migrations.DeleteModel(
            name='DeckShare',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserDeck',
        ),
    ]
