# Generated by Django 4.0.4 on 2024-11-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='decks_in_curriculum',
        ),
        migrations.AddField(
            model_name='profile',
            name='decks_in_curriculum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(max_length=100),
        ),
    ]
