# Generated by Django 4.2.16 on 2024-11-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_deckshare_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
    ]
