# Generated by Django 4.2.16 on 2024-11-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
