# Generated by Django 4.2.16 on 2024-11-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_userdeck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='study_streak',
        ),
    ]
