# Generated by Django 4.2.16 on 2024-11-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_remove_profile_study_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdeck',
            name='user',
        ),
        migrations.AddField(
            model_name='userdeck',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_deck', to='cards.profile'),
            preserve_default=False,
        ),
    ]
