# Generated by Django 4.2.16 on 2024-11-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_userdeck_user_userdeck_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardprogress',
            name='review_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
